#This program evaluates the answer to the Euler Project Problem 2
=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

#first here is the pseudocode 

#Generate a Fibonacci sequence and store in an array such that [-1] > four million
#lamda an expression to total the evn sumbers

puts "This program will sum the even numbers in a generate Fibonacci sequence in which you define the upper limit"
puts "Please enter the upper bound of the Fibonacci sequence you would like to sum."

upper_bound = gets.to_i


#Recursion is too computationally intensive. We will use iteration. More memory intensive but quicker. 

sum,a,b = 0,0,1
while b < upper_bound
	sum += b if b.even?
	a,b = b, a + b
end

puts sum

	




